services:
  application:
    build:
      context: .
      args:
        options: --reload
    environment:
      - PORT=8080
      - URL=http://0.0.0.0:8080
      - SERVICE_ENVIRONMENT=dev
      - DB_USERNAME=db_user
      - DB_PASSWORD=db_password
      - DB_HOST=first_db
      - DB_PORT=3306
      - DB_DATABASE=first_db
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - test-network
      
  db:
    image: public.ecr.aws/docker/library/mysql:8.0.35
    environment:
      - MYSQL_ROOT_PASSWORD=db_password
      - MYSQL_DATABASE=first_db
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "first_db", "-udb_user", "-pdb_password" ]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
