services:
  demo-app:
    build:
      context: .
      args:
        options: --reload
    environment:
      - PORT=8080
      - URL=http://0.0.0.0:8080
      - SERVICE_ENVIRONMENT=dev
      - DB_USERNAME=db_user
      - DB_PASSWORD=db_password
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=first_db
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      swagger-ui:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - test-network

  db:
    image: public.ecr.aws/docker/library/mysql:8.0.35
    environment:
      - MYSQL_ROOT_PASSWORD=db_password
      - MYSQL_DATABASE=first_db
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "db", "-udb_user", "-pdb_password" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - test-network
  swagger-ui:
    image: swaggerapi/swagger-ui:v5.29.5
    ports:
        - "8081:8080"
    environment:
      - SWAGGER_JSON=/openapi/openapi.yaml
    volumes:
      - ./documentation/openapi:/openapi
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - test-network
  redis:
    image: public.ecr.aws/docker/library/redis:8.4-rc1-alpine3.22
    container_name: redis_limiter
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
